apiVersion: v1
kind: Service
metadata:
  name: milk-app-service
spec:
  selector:
    app: milk-app-deploy
  type: ClusterIP    
  ports:
  - name: service-port
    protocol: TCP
    port: 5000
    targetPort: deploy-port
