name: Build and Deploy image

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./script/Dockerfile
        push: true
        tags: |
          darrenchange/milk-app:latest
          darrenchange/milk-app:${{ github.ref_name }}
        platforms: linux/amd64,linux/arm64

  deploy-k8s:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Kubectl
      uses: azure/setup-kubectl@v1

    - name: Configure Kubeconfig
      uses: azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBECONFIG }}

    - name: Create and Apply Kubernetes Secret
      run: |
        kubectl create secret generic milk-secret \
          --from-literal=PRIVATE_GROUP_ID="${{ secrets.PRIVATE_GROUP_ID }}" \
          --from-literal=LINE_ACCESS_TOKEN="${{ secrets.LINE_ACCESS_TOKEN }}" \
          --from-literal=LINE_SECRET="${{ secrets.LINE_SECRET }}" \
          --from-literal=LINE_NOTIFY_TOKEN="${{ secrets.LINE_NOTIFY_TOKEN }}" \
          --from-literal=POSTGRES_USER="${{ secrets.POSTGRES_USER }}" \
          --from-literal=POSTGRES_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}" \
          --from-literal=POSTGRES_SERVER="${{ secrets.POSTGRES_SERVER }}" \
          --from-literal=POSTGRES_DB="${{ secrets.POSTGRES_DB }}" \
          --from-literal=TZ="${{ secrets.TZ }}" \
          --dry-run=client -o yaml | kubectl apply -f -
    
    - name: Deploy Application to Kubernetes
      run: |
        sed -i "s|darrenchange/milk-app:latest|darrenchange/milk-app:${{ github.ref_name }}|g" script/k8s/deployment.yaml
        kubectl apply -f script/k8s/
